// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-QDEaAkdMseFfZ_TJxiqx3ewS6ZPpWZM',
    appId: '1:84719770833:web:dceb11ab1e44f9fab9b9f0',
    messagingSenderId: '84719770833',
    projectId: 'chat-app-ac1c9',
    authDomain: 'chat-app-ac1c9.firebaseapp.com',
    storageBucket: 'chat-app-ac1c9.appspot.com',
    measurementId: 'G-1WD6TDYG7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8eew3dICSHgvbybYnqL-2-tiJu-huZng',
    appId: '1:84719770833:android:9a75fbc2dbfe40aab9b9f0',
    messagingSenderId: '84719770833',
    projectId: 'chat-app-ac1c9',
    storageBucket: 'chat-app-ac1c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCubr8Ge_b0F9SgiRQ06f_r1iSwUXveLw',
    appId: '1:84719770833:ios:e0da322b5c3c31e2b9b9f0',
    messagingSenderId: '84719770833',
    projectId: 'chat-app-ac1c9',
    storageBucket: 'chat-app-ac1c9.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCubr8Ge_b0F9SgiRQ06f_r1iSwUXveLw',
    appId: '1:84719770833:ios:28c32b9db7785468b9b9f0',
    messagingSenderId: '84719770833',
    projectId: 'chat-app-ac1c9',
    storageBucket: 'chat-app-ac1c9.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
